export const PERMISSION_CODES = {
  USERS_READ: "USERS_READ",
  USERS_MANAGE: "USERS_MANAGE",

  DEPARTMENTS_READ: "DEPARTMENTS_READ",
  DEPARTMENTS_MANAGE: "DEPARTMENTS_MANAGE",

  MEMBERS_READ: "MEMBERS_READ",
  MEMBERS_MANAGE: "MEMBERS_MANAGE",

  PROJECTS_READ: "PROJECTS_READ",
  PROJECTS_MANAGE: "PROJECTS_MANAGE",

  TASKS_READ: "TASKS_READ",
  TASKS_CREATE: "TASKS_CREATE",
  TASKS_UPDATE: "TASKS_UPDATE",
  TASKS_ASSIGN: "TASKS_ASSIGN",
  TASKS_STATUS_CHANGE: "TASKS_STATUS_CHANGE",

  COMMENTS_CREATE: "COMMENTS_CREATE",

  ACTIVITY_READ: "ACTIVITY_READ",

  NOTIFICATIONS_READ: "NOTIFICATIONS_READ",
} as const;

export type PermissionCode =
  (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];
